/**
 * Copyright IBM Corp. 2018, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

/**
 * Style Dictionary format — carbon/js-layout
 *
 * Emits either:
 *   - An ES module (.js)  with `export const camelName = value;`
 *   - A TypeScript declaration file (.d.ts) with `export declare const camelName: string;`
 *
 * Token names arrive as kebab-case from SD (e.g. "spacing-01") and are
 * converted to camelCase ("spacing01") so the output matches the existing
 * hand-authored exports in src/index.ts.
 */

const FILE_BANNER = `// Code generated by @carbon/layout. DO NOT EDIT.
//
// Copyright IBM Corp. 2018, 2026
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.
`;

/**
 * Convert kebab-case to camelCase.
 * "spacing-01"       → "spacing01"
 * "fluid-spacing-02" → "fluidSpacing02"
 * "border-radius-08" → "borderRadius08"
 * "size-xs"          → "sizeXs"  (kept for completeness; index re-exports under SizeName aliases)
 * "icon-size-01"     → "iconSize01"
 * "layout-03"        → "layout03"
 *
 * @param {string} str
 * @returns {string}
 */
function kebabToCamel(str) {
  return str.replace(/-([a-z0-9])/g, (_, ch) => ch.toUpperCase());
}

/**
 * @param {{ dictionary: import('style-dictionary').Dictionary, options: object }} args
 * @returns {string}
 */
function carbonJsLayoutFormat({ dictionary, options }) {
  const outputMode = options?.output ?? 'js'; // 'js' | 'dts'
  const lines = [FILE_BANNER];

  for (const token of dictionary.allTokens) {
    const camelName = kebabToCamel(token.name);
    // Unitless zero — preserve as number 0, not the string "0", to match the
    // original hand-authored export: `export const fluidSpacing01 = 0`
    const resolved = token.$value === '0' ? 0 : token.$value;

    const tsType = resolved === 0 ? 'number' : 'string';
    if (outputMode === 'js') {
      // Numeric 0 is emitted bare (no quotes) to preserve the original type.
      const src = resolved === 0 ? '0' : `'${resolved}'`;
      lines.push(`export const ${camelName} = ${src};`);
    } else {
      lines.push(`export declare const ${camelName}: ${tsType};`);
    }
  }

  return lines.join('\n') + '\n';
}

module.exports = {
  name: 'carbon/js-layout',
  format: carbonJsLayoutFormat,
};
