/**
 * Copyright IBM Corp. 2018, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

/**
 * Style Dictionary format — carbon/js-layout
 *
 * Emits either:
 *   - An ES module (.js)  with `export const camelName = value;`
 *   - A TypeScript declaration file (.d.ts) with `export declare const camelName: string;`
 *
 * Token names arrive as kebab-case from SD (e.g. "spacing-01") and are
 * converted to camelCase ("spacing01") so the output matches the existing
 * hand-authored exports in src/index.ts.
 */

const FILE_BANNER = `// Code generated by @carbon/layout. DO NOT EDIT.
//
// Copyright IBM Corp. 2018, 2026
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.
`;

/**
 * Convert kebab-case to camelCase.
 * "spacing-01"       → "spacing01"
 * "fluid-spacing-02" → "fluidSpacing02"
 * "border-radius-08" → "borderRadius08"
 * "size-xs"          → "sizeXs"  (kept for completeness; index re-exports under SizeName aliases)
 * "icon-size-01"     → "iconSize01"
 * "layout-03"        → "layout03"
 *
 * @param {string} str
 * @returns {string}
 */
function kebabToCamel(str) {
  return str.replace(/-([a-z0-9])/g, (_, ch) => ch.toUpperCase());
}

const BASE_FONT_SIZE = 16;
const MINI_UNIT = 8;

/**
 * Resolve a token's raw $value using the carbon.layout.converter extension.
 * - "miniUnits": steps × 8px ÷ 16 → rem string
 * - "rem":       px ÷ 16 → rem string
 * - (none):      value is already a resolved CSS string, returned as-is
 *
 * @param {string|number} value
 * @param {object|undefined} carbonLayout  — token.$extensions?.['carbon.layout']
 * @returns {string}
 */
function resolveValue(value, carbonLayout) {
  const converter = carbonLayout?.converter;
  if (converter === 'miniUnits') {
    return `${(Number(value) * MINI_UNIT) / BASE_FONT_SIZE}rem`;
  }
  if (converter === 'rem') {
    return `${Number(value) / BASE_FONT_SIZE}rem`;
  }
  // Unitless zero — preserve as number 0, not the string "0", to match the
  // original hand-authored export: `export const fluidSpacing01 = 0`
  if (value === '0' || value === 0) return 0;
  return String(value);
}

/**
 * @param {{ dictionary: import('style-dictionary').Dictionary, options: object }} args
 * @returns {string}
 */
function carbonJsLayoutFormat({ dictionary, options }) {
  const outputMode = options?.output ?? 'js'; // 'js' | 'dts'
  const lines = [FILE_BANNER];

  for (const token of dictionary.allTokens) {
    const camelName = kebabToCamel(token.name);
    const carbonLayout =
      token.$extensions?.['carbon.layout'] ??
      token.extensions?.['carbon.layout'];
    const resolved = resolveValue(token.value ?? token.$value, carbonLayout);

    const tsType = resolved === 0 ? 'number' : 'string';
    if (outputMode === 'js') {
      // Numeric 0 is emitted bare (no quotes) to preserve the original type.
      const src = resolved === 0 ? '0' : `'${resolved}'`;
      lines.push(`export const ${camelName} = ${src};`);
    } else {
      lines.push(`export declare const ${camelName}: ${tsType};`);
    }
  }

  return lines.join('\n') + '\n';
}

module.exports = {
  name: 'carbon/js-layout',
  format: carbonJsLayoutFormat,
};
