/**
 * Copyright IBM Corp. 2018, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

/**
 * Style Dictionary format — carbon/scss-layout
 *
 * Generates per-category Sass files from layout.json whose content is
 * byte-for-byte identical to what build.mjs / @carbon/scss-generator produced,
 * so that nothing downstream breaks.
 *
 * Files emitted:
 *   _spacing.scss        variables + map, !default
 *   _fluid-spacing.scss  variables + map, !default
 *   _container.scss      variables + map, !default
 *   _icon-size.scss      variables + map, !default
 *   _border-radius.scss  variables + map, !default
 *   _layout.scss         variables + map, !default  (deprecated tokens)
 *   _size.scss           bare assignments, no !default, no map
 */

// ── Banners ───────────────────────────────────────────────────────────────────
// Most files use 2023; _size.scss uses 2026 — match exactly.
const BANNER_2023 = `// Code generated by @carbon/layout. DO NOT EDIT.
//
// Copyright IBM Corp. 2018, 2023
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.
//`;

const BANNER_2026 = `// Code generated by @carbon/layout. DO NOT EDIT.
//
// Copyright IBM Corp. 2018, 2026
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.
//`;

const VAR_COMMENT = `/// @type Number
/// @access public
/// @group @carbon/layout`;

const MAP_COMMENT = `/// @type Map
/// @access public
/// @group @carbon/layout`;

// ── Constants ─────────────────────────────────────────────────────────────────
const BASE_FONT_SIZE = 16;
const MINI_UNIT = 8;

/**
 * Resolve a token's $value using carbon.layout.converter if present.
 * @param {string|number} value
 * @param {object|undefined} carbonLayout
 * @returns {string}
 */
function resolveValue(value, carbonLayout) {
  const converter = carbonLayout?.converter;
  if (converter === 'miniUnits') {
    return `${(Number(value) * MINI_UNIT) / BASE_FONT_SIZE}rem`;
  }
  if (converter === 'rem') {
    return `${Number(value) / BASE_FONT_SIZE}rem`;
  }
  return String(value);
}

/**
 * Build a standard file: banner + (comment + $var: value !default;) * n + map.
 * @param {Array<{name: string, resolved: string}>} tokens
 * @param {string} mapName  — Sass map variable name
 * @param {string} banner
 * @returns {string}
 */
function buildStandardFile(tokens, mapName, banner) {
  const lines = [banner, ''];

  for (const { name, resolved } of tokens) {
    lines.push(VAR_COMMENT);
    lines.push(`$${name}: ${resolved} !default;`);
    lines.push('');
  }

  lines.push(MAP_COMMENT);
  lines.push(`$${mapName}: (`);
  for (const { name } of tokens) {
    lines.push(`  ${name}: $${name},`);
  }
  lines.push(');');

  return lines.join('\n') + '\n';
}

/**
 * Build _size.scss — no !default, no map, no per-variable comments.
 * @param {Array<{name: string, resolved: string}>} tokens
 * @returns {string}
 */
function buildSizeFile(tokens) {
  const lines = [BANNER_2026, ''];
  lines.push(VAR_COMMENT);
  for (const { name, resolved } of tokens) {
    lines.push(`$${name}: ${resolved};`);
  }
  return lines.join('\n') + '\n';
}

/**
 * Extract tokens belonging to a DTCG group from the SD dictionary.
 * Routing is done by token.path[0] — the group name in the JSON — which is
 * the native DTCG mechanism. No prefix inference needed.
 *
 * @param {import('style-dictionary').Dictionary} dictionary
 * @param {string} groupName  — top-level DTCG group key (e.g. "spacing")
 * @returns {Array<{name: string, resolved: string}>}
 */
function tokensForGroup(dictionary, groupName) {
  return dictionary.allTokens
    .filter((t) => t.path[0] === groupName)
    .map((t) => {
      const carbonLayout =
        t.$extensions?.['carbon.layout'] ?? t.extensions?.['carbon.layout'];
      return {
        name: t.name,
        resolved: resolveValue(t.value ?? t.$value, carbonLayout),
      };
    });
}

// ── Format functions — one per DTCG group ─────────────────────────────────────

function formatSpacing({ dictionary }) {
  const tokens = tokensForGroup(dictionary, 'spacing');
  return buildStandardFile(tokens, 'spacing', BANNER_2023);
}

function formatFluidSpacing({ dictionary }) {
  const tokens = tokensForGroup(dictionary, 'fluid-spacing');
  // Sass expects unitless 0, not the string "0"
  const fixed = tokens.map((t) => ({
    ...t,
    resolved: t.resolved === '0' ? '0' : t.resolved,
  }));
  return buildStandardFile(fixed, 'fluid-spacing', BANNER_2023);
}

function formatContainer({ dictionary }) {
  const tokens = tokensForGroup(dictionary, 'container');
  return buildStandardFile(tokens, 'container', BANNER_2023);
}

function formatIconSize({ dictionary }) {
  const tokens = tokensForGroup(dictionary, 'icon-size');
  return buildStandardFile(tokens, 'icon-size', BANNER_2023);
}

function formatBorderRadius({ dictionary }) {
  const tokens = tokensForGroup(dictionary, 'border-radius');
  return buildStandardFile(tokens, 'border-radius', BANNER_2023);
}

function formatLayout({ dictionary }) {
  const tokens = tokensForGroup(dictionary, 'layout');
  return buildStandardFile(tokens, 'layout', BANNER_2023);
}

function formatSize({ dictionary }) {
  const tokens = tokensForGroup(dictionary, 'size');
  return buildSizeFile(tokens);
}

// ── Exports ───────────────────────────────────────────────────────────────────

module.exports = [
  { name: 'carbon/scss-spacing', format: formatSpacing },
  { name: 'carbon/scss-fluid-spacing', format: formatFluidSpacing },
  { name: 'carbon/scss-container', format: formatContainer },
  { name: 'carbon/scss-icon-size', format: formatIconSize },
  { name: 'carbon/scss-border-radius', format: formatBorderRadius },
  { name: 'carbon/scss-layout', format: formatLayout },
  { name: 'carbon/scss-size', format: formatSize },
];
