/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import styles from './tile.scss';

/**
 * Tile group.
 *
 * @element cds-tile-group
 */
@customElement(`${prefix}-tile-group`)
class BXTileGroup extends LitElement {
  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'group');
    }
    super.connectedCallback();
  }

  render() {
    return html`
      <slot name="legend" class="${prefix}--label"></slot>
      <slot></slot>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default BXTileGroup;
