coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

component_management:
  default_rules: # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        threshold: 1%
        branches:
          - '!main'
  individual_components:
    - component_id: colors
      name: colors
      paths:
        - ../packages/colors/**
    - component_id: feature-flags
      name: feature-flags
      paths:
        - ../packages/feature-flags/**
    - component_id: icon-build-helpers
      name: icon-build-helpers
      paths:
        - ../packages/icon-build-helpers/**
    - component_id: layout
      name: layout
      paths:
        - ../packages/layout/**
    - component_id: motion
      name: motion
      paths:
        - ../packages/motion/**
    - component_id: react # this is an identifier that should not be changed
      name: react # this is a display name, and can be changed freely
      paths:
        - ../packages/react/**
    - component_id: scss-generator
      name: scss-generator
      paths:
        - ../packages/scss-generator/**
    - component_id: test-utils
      name: test-utils
      paths:
        - ../packages/test-utils/**
    - component_id: themes
      name: themes
      paths:
        - ../packages/themes/**
    - component_id: type
      name: type
      paths:
        - ../packages/type/**
    - component_id: upgrade
      name: upgrade
      paths:
        - ../packages/upgrade/**
