# Configuration for Label Actions - https://github.com/dessant/label-actions

# The `enhancement` label is added to issues
enhancement:
  # Post a comment
  comment: >
    Thank you for submitting a feature request. Here’s what to expect next. 
    Your proposal is open and is now being [triaged](https://github.com/orgs/carbon-design-system/projects/51/views/1) by the Carbon team. 
    If your proposal is accepted and the Carbon team has bandwidth they will take on the issue, or else request volunteers from the community. 
    Read the full triaging workflow [here](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/support.md#type-enhancement-).
  # Option to lock the thread
  lock: false