# This is the config file for the github/issue-labeler action, which is used in
# the issue-triage-labeler.yml workflow.
#
# Keys within this file are the name of the label in the repository that we want
# to add (eg: "package: styles", "severity: 1") and the value is the regular
# expression for when to apply the label. Should the regular expression not
# match, the label will not be applied.
#
# This only adds labels. Labels are not removed if the regex doesn't match. This
# is because we do not configure `sync-labels: 1` in the workflow file.
#
# When changes are made to this file, consider updating the `not-before` config
# in the workflow file to match the day you open the PR of your changes. This
# will ensure that only new issues moving forward are labelled with the contents
# of this file.
#
# @see https://github.com/marketplace/actions/regex-issue-labeler

# a11y labels, case insensitive
'a11y: high contrast mode':
  - '/(high contrast)/i'
'a11y: JAWS':
  - '/(jaws)/i'
'a11y: NVDA':
  - '/(nvda)/i'
'a11y: TalkBack':
  - '/(talkback)/i'
'a11y: VoiceOver':
  - '/(voiceover)/i'

# Adopter labels
# Add 'adopter: strategic-product' label if issue contains any of these
# project names. Case insensitive.
'adopter: strategic-product':
  - '/(API Connect|Turbonomic|Instana|NS1|watsonx Orchestrate|watsonx Code
    Assistant|Planning Analytics|SPSS
    Statistics|watsonx\.data|watsonx\.ai|watsonx\.governance|Maximo Application
    Suite|Environmental Intelligence Suite|Envizi ESG Suite|QRadar Log
    Insights|QRadar XDR/EDR \(ReaQta\)|Randori ASM|QRadar
    SIEM|MaaS360|Flash|Defender|Fusion|APP Connect|Apptio Cloudability|Apptio
    Targetprocess|AIOps Insights|Hybrid Cloud Mesh|Aspera|Blueworks
    Live|OpenPages|Databand\.ai|Cognos Analytics|Sterling B2B Integration
    SaaS|Sterling Order & Inventory Management|Supply Chain Intelligence
    Suite|TRIRIGA Application Suite|QRadar SOAR|Guardium Insights|Verify on
    Cloud|DataPower)/i'

# Browser labels, case insensitive
'browser: chrome':
  - '/(chrome)/i'
'browser: firefox':
  - '/(firefox)/i'
'browser: safari':
  - '/(safari)/i'

# Status labels
'status: needs design spec':
  - '(Yes, (visual design|user interaction|both visual and interaction)|- \[x\]
    The website documentation \(carbondesignsystem\.com\)|- \[x\] Figma kit
    documentation|- \[x\] Storybook\(s\) documentation)'

# Package labels
'package: @carbon/labs':
  - '(@carbon/labs)'
'package: @carbon/react':
  - '(@carbon/react)'
'package: @carbon/web-components':
  - '(@carbon/web-components)'
'package: browserslist-config-carbon':
  - '(browserslist-config-carbon)'
'package: bundler':
  - '(@carbon/bundler)'
'package: cli':
  - '(@carbon/cli)'
'package: cli-reporter':
  - '(@carbon/cli-reporter)'
'package: colors':
  - '(@carbon/colors)'
'package: components':
  - '(carbon-components)'
'package: elements':
  - '(@carbon/elements)'
'package: eslint-config-carbon':
  - '(eslint-config-carbon)'
'package: feature-flags':
  - '(@carbon/feature-flags)'
'package: grid':
  - '(@carbon/grid)'
'package: icon-build-helpers':
  - '(@carbon/icon-build-helpers)'
'package: icon-helpers':
  - '(@carbon/icon-helpers)'
'package: icons':
  - '(@carbon/icons)'
'package: icons-angular':
  - '(@carbon/icons-angular)'
'package: icons-handlebars':
  - '(@carbon/icons-handlebars)'
'package: icons-react':
  - '(@carbon/icons-react)'
'package: icons-vue':
  - '(@carbon/icons-vue)'
'package: import-once':
  - '(@carbon/import-once)'
'package: layout':
  - '(@carbon/layout)'
'package: motion':
  - '(@carbon/motion)'
'package: pictograms':
  - '(@carbon/pictograms)'
'package: pictograms-react':
  - '(@carbon/pictograms-react)'
'package: react':
  - '(carbon-components-react)'
'package: scss-generator':
  - '(@carbon/scss-generator)'
'package: sketch':
  - '(@carbon/sketch)'
'package: stylelint-config-elements':
  - '(@carbon/stylelint-config-elements)'
'package: styles':
  - '(@carbon/styles)'
'package: text-utils':
  - '(@carbon/text-utils)'
'package: themes':
  - '(@carbon/themes)'
'package: type':
  - '(@carbon/type)'
'package: upgrade':
  - '(@carbon/upgrade)'

# Platform labels
'platform: android':
  - '/(android)/i'
'platform: ios':
  - '/(ios)/i'
'platform: macos':
  - '/(macos)/i'
'platform: windows':
  - '/(windows)/i'

# Severity labels
severity 1:
  - '(Severity 1 = Must be fixed ASAP)'
severity 2:
  - '(Severity 2 = User cannot complete task)'
severity 3:
  - '(Severity 3 = User can complete task)'
severity 4:
  - '(Severity 4 = Unrelated to a user task)'
