/**
 * Copyright IBM Corp. 2018, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

// colors.js is generated by tasks/build.js from src/dtcg/colors.json.
// Run `yarn build` to generate it before bundling.
export * from '../js/generated/colors.js';
export * from './rgb';
