nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

supportedArchitectures:
  os:
    - 'current'
    - 'darwin'
    - 'linux'
    - 'win32'
  cpu:
    - 'current'
    - 'x64'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
