import React from 'react';
import { NotificationCallout } from './NotificationCallout';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  NotificationCallout,
  'https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-Carbon-Design-System?node-id=84336-36580&t=nJ89fkK549fgCUuf-4',
  {
    props: {
      title: figma.boolean('Title'),
      messageText: figma.string('Message text'),
      titleText: figma.string('Title text'),
      status: figma.enum('Status', {
        Info: 'info',
        Warning: 'warning',
      }),
      highContrast: figma.boolean('High contrast'),
      longMessage: figma.boolean('Long message'),
    },
    example: (props) => <NotificationCallout />,
  }
);
