/**
 * Copyright IBM Corp. 2015, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

const { reporter } = require('@carbon/cli-reporter');
const { generate } = require('@carbon/scss-generator');
const fs = require('fs-extra');
const path = require('path');
const buildCompatThemesFile = require('./builders/compat/themes');
const buildCompatTokensFile = require('./builders/compat/tokens');
const generateDTCGColorAliases = require('./builders/generate-dtcg-color-aliases');
const { runScss } = require('../style-dictionary/sd.config');

async function build() {
  reporter.info('Building scss files for themes...');

  // Stage 1 — generate color-palette.json from @carbon/colors (unchanged).
  reporter.info('Generating DTCG color palette aliases from @carbon/colors...');
  const paletteFile = generateDTCGColorAliases();
  reporter.success(`Written: ${paletteFile}`);

  const SCSS_DIR = path.resolve(__dirname, '../scss');

  // Compat layer — still generated by the hand-authored builders.
  const compatFiles = [
    {
      filepath: path.join(SCSS_DIR, 'compat', 'generated', '_themes.scss'),
      builder() {
        return buildCompatThemesFile();
      },
    },
    {
      filepath: path.resolve(SCSS_DIR, 'compat', 'generated', '_tokens.scss'),
      builder() {
        return buildCompatTokensFile();
      },
    },
  ];

  for (const { filepath, builder } of compatFiles) {
    await fs.ensureFile(filepath);
    const { code } = generate(builder());
    await fs.writeFile(filepath, await code);
  }

  // DTCG layer — now generated by the Style Dictionary pipeline.
  reporter.info('Generating DTCG SCSS files via Style Dictionary...');
  await runScss();

  reporter.success('Done! 🎉');
}

build().catch((error) => {
  console.error(error);
  process.exit(1);
});
