import React from 'react';
import { Modal } from './Modal';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Modal,
  'https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?node-id=4080-55366&t=kgHdN1kQbk04e5Jv-4',
  {
    props: {
      titletext11555621: figma.string('Title text'),
      swapslot11555603: figma.instance('Swap slot'),
      progress11555591: figma.boolean('Progress'),
      description326306: figma.boolean('Description'),
      slot11555609: figma.boolean('Slot'),
      actions11555552: figma.boolean('Actions'),
      closeicon11555510: figma.boolean('Close icon'),
      descriptiontext11555597: figma.string('Description text'),
      label11555343: figma.boolean('Label'),
      labeltext11555176: figma.string('Label text'),
      size: figma.enum('Size', {
        Large: 'large',
        Medium: 'medium',
        Small: 'small',
        'Extra small': 'extra-small',
        Mobile: 'mobile',
      }),
    },
    example: (props) => <Modal />,
  }
);
