import { fontFamilies, fontFamily } from './fontFamily';
import { fontWeights, fontWeight } from './fontWeight';
import { print } from './print';
import { reset } from './reset';
import { getTypeSize, scale } from './scale';
import { spacing } from './spacing';
import {
  caption01,
  label01,
  helperText01,
  bodyShort01,
  bodyLong01,
  bodyShort02,
  bodyLong02,
  code01,
  code02,
  heading01,
  heading02,
  heading03,
  productiveHeading04,
  productiveHeading05,
  expressiveHeading04,
  expressiveHeading05,
  quotation01,
  quotation02,
  display01,
  display02,
  display03,
  display04,
} from './styles';

export {
  fontFamilies,
  fontFamily,
  fontWeights,
  fontWeight,
  print,
  reset,
  getTypeSize,
  scale,
  spacing,
  // Tokens
  caption01,
  label01,
  helperText01,
  bodyShort01,
  bodyLong01,
  bodyShort02,
  bodyLong02,
  code01,
  code02,
  heading01,
  heading02,
  heading03,
  productiveHeading04,
  productiveHeading05,
  expressiveHeading04,
  expressiveHeading05,
  quotation01,
  quotation02,
  display01,
  display02,
  display03,
  display04,
};
