import '../scss/styles.scss';
import { ThemePreference } from '../components/ThemePreference';

export const metadata = {
  title: 'Light/Dark Mode Example',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <ThemePreference>{children}</ThemePreference>
      </body>
    </html>
  );
}
