/**
 * Copyright IBM Corp. 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { StoryDocsPage } from '../../global/js/utils/StoryDocsPage';

import * as stories from './ExpressiveCard.stories';

const DocsPage = () => (
  <StoryDocsPage
    altGuidelinesHref="https://pages.github.ibm.com/carbon/ibm-products/components/card/expressive-card/usage/"
    blocks={[
      {
        story: stories.Default,
      },
      {
        story: stories.Clickable,
      },
      {
        story: stories.LabelOnly,
      },
      {
        story: stories.WithActionIconLink,
      },
      {
        story: stories.WithButtonHref,
      },
      {
        story: stories.WithButtonIcon,
      },
      {
        story: stories.WithCaption,
      },
      {
        story: stories.WithMedia,
      },
      {
        story: stories.WithPictogram,
      },
      {
        story: stories.WithSecondaryAction,
      },
      {
        title: 'With AI Label',
        description:
          'An AI Label is intended for any scenario where something is being generated by AI to reinforce AI transparency, accountability, and explainability at the UI level.',
        source: {
          language: 'html',
          code: `
      <ExpressiveCard
  label="Label"
  primaryButtonText="Primary"
  decorator={<AILabel><AILabelContent>{renderedContent}</AILabelContent></AILabel>}
  title="Title">
  <p>
    expressive card body content block. description inviting the user to take action on the card.
  </p>
</ExpressiveCard>
          `,
        },
      },
      {
        description:
          'Clickable tiles only accept a boolean value of true for the decorator property.',
        source: {
          language: 'html',
          code: `
      <ExpressiveCard
  label="Label"
  primaryButtonText="Primary"
  onClick={() => {}}
  onKeyDown={() => {}}
  decorator={true}
  title="Title">
  <p>
    expressive card body content block. description inviting the user to take action on the card.
  </p>
</ExpressiveCard>
          `,
        },
      },
    ]}
  />
);

export default DocsPage;
