/**
 * Copyright IBM Corp. 2025, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

exports.reactPreviewMap = {
  unstable_FeatureFlags: 'preview_FeatureFlags',
  unstable_useFeatureFlag: 'preview_useFeatureFlag',
  unstable_useFeatureFlags: 'preview_useFeatureFlags',
  unstable__PageHeader: 'preview__PageHeader',
  unstable__FluidComboBox: 'preview__FluidComboBox',
  unstable__FluidComboBoxSkeleton: 'preview__FluidComboBoxSkeleton',
  unstable__FluidDatePicker: 'preview__FluidDatePicker',
  unstable__FluidDatePickerSkeleton: 'preview__FluidDatePickerSkeleton',
  unstable__FluidDatePickerInput: 'preview__FluidDatePickerInput',
  unstable__FluidDropdown: 'preview__FluidDropdown',
  unstable__FluidDropdownSkeleton: 'preview__FluidDropdownSkeleton',
  unstable__FluidMultiSelect: 'preview__FluidMultiSelect',
  unstable__FluidMultiSelectSkeleton: 'preview__FluidMultiSelectSkeleton',
  unstable__FluidSelect: 'preview__FluidSelect',
  unstable__FluidSelectSkeleton: 'preview__FluidSelectSkeleton',
  unstable__FluidSearch: 'preview__FluidSearch',
  unstable__FluidSearchSkeleton: 'preview__FluidSearchSkeleton',
  unstable__FluidTextArea: 'preview__FluidTextArea',
  unstable__FluidTextAreaSkeleton: 'preview__FluidTextAreaSkeleton',
  unstable__FluidTextInput: 'preview__FluidTextInput',
  unstable__FluidTextInputSkeleton: 'preview__FluidTextInputSkeleton',
  unstable__FluidTimePicker: 'preview__FluidTimePicker',
  unstable__FluidNumberInput: 'preview__FluidNumberInput',
  unstable__FluidNumberInputSkeleton: 'preview__FluidNumberInputSkeleton',
  unstable__FluidTimePickerSkeleton: 'preview__FluidTimePickerSkeleton',
  unstable__FluidTimePickerSelect: 'preview__FluidTimePickerSelect',
  unstable_LayoutDirection: 'preview_LayoutDirection',
  unstable_useLayoutDirection: 'preview_useLayoutDirection',
  unstable_Layout: 'preview_Layout',
  unstable_PageSelector: 'preview_PageSelector',
  unstable_Pagination: 'preview_Pagination',
  unstable__IconIndicator: 'preview__IconIndicator',
  unstable__ShapeIndicator: 'preview__ShapeIndicator',
  unstable__Slug: 'preview__Slug',
  unstable__SlugContent: 'preview__SlugContent',
  unstable__SlugActions: 'preview__SlugActions',
  unstable__ChatButton: 'preview__ChatButton',
  unstable__ChatButtonSkeleton: 'preview__ChatButtonSkeleton',
  unstable__AiSkeletonText: 'preview__AiSkeletonText',
  unstable__AiSkeletonIcon: 'preview__AiSkeletonIcon',
  unstable__AiSkeletonPlaceholder: 'preview__AiSkeletonPlaceholder',
  unstable_Text: 'preview_Text',
  unstable_TextDirection: 'preview_TextDirection',
};

exports.productsPreviewMap = {
  BigNumber: 'previewCandidate__BigNumber',
  BigNumbers: 'previewCandidate__BigNumber',
  Coachmark: 'previewCandidate__Coachmark',
  CoachmarkBeacon: 'previewCandidate__CoachmarkBeacon',
  CoachmarkButton: 'previewCandidate__CoachmarkButton',
  CoachmarkFixed: 'previewCandidate__CoachmarkFixed',
  CoachmarkOverlayElement: 'previewCandidate__CoachmarkOverlayElement',
  CoachmarkOverlayElements: 'previewCandidate__CoachmarkOverlayElements',
  CoachmarkStack: 'previewCandidate__CoachmarkStack',
  ConditionBuilder: 'previewCandidate__ConditionBuilder',
  DataSpreadsheet: 'previewCandidate__DataSpreadsheet',
  Decorator: 'previewCandidate__Decorator',
  DelimitedList: 'previewCandidate__DelimitedList',
  GetStartedCard: 'previewCandidate__GetStartedCard',
  GuideBanner: 'previewCandidate__Guidebanner',
  GuidebannerElement: 'previewCandidate__GuidebannerElement',
  GuidebannerElementButton: 'previewCandidate__GuidebannerElementButton',
  GuidebannerElementLink: 'previewCandidate__GuidebannerElementLink',
  InlineTip: 'previewCandidate__InlineTip',
  InlineTipButton: 'previewCandidate__InlineTipButton',
  InlineTipLink: 'previewCandidate__InlineTipLink',
  NonLinearReading: 'previewCandidate__NonLinearReading',
  SearchBar: 'previewCandidate__SearchBar',
  Toolbar: 'previewCandidate__Toolbar',
  ToolbarButton: 'previewCandidate__ToolbarButton',
  ToolbarGroup: 'previewCandidate__ToolbarGroup',
  TruncatedList: 'previewCandidate__TruncatedList',
};
