/**
 * Copyright IBM Corp. 2024, 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { StoryDocsPage } from '../../global/js/utils/StoryDocsPage';

import * as stories from './SidePanel.stories';

const DocsPage = () => (
  <StoryDocsPage
    blocks={[
      {
        title: 'Feature flags',
        description:
          'The SidePanel supports resizable feature through feature flag. The feature can be enabled by wrapping the component with `FeatureFlags` component and passing the `enableSidepanelResizer` flag as a prop. the feature can be seen in action in the stories by enabling the `enableSidepanelResizer` flag in the controls panel.',
        source: {
          language: 'jsx',
          code: `
import { preview__FeatureFlags as FeatureFlags } from '@carbon/ibm-products';
...
<FeatureFlags enableSidepanelResizer>
  <SidePanel
    {...args}
  >
    ...
  </SidePanel>
</FeatureFlags>
                `,
        },
      },
      {
        story: stories.SlideOver,
      },
      {
        story: stories.SlideIn,
      },
      {
        story: stories.WithActionToolbar,
      },
      {
        story: stories.PanelWithSecondStep,
      },
      {
        story: stories.SpecifyElementToHaveInitialFocus,
      },
      {
        story: stories.WithStaticTitle,
      },
      {
        story: stories.FirstElementDisabled,
      },
      {
        story: stories.WithStaticTitleAndActionToolbar,
      },
      {
        story: stories.WithoutTitle,
      },
      {
        title: 'With AI Label',
        story: stories.WithAILabel,
        description:
          'An AI Label is intended for any scenario where something is being generated by AI to reinforce AI transparency, accountability, and explainability at the UI level. A Carbon AI Label can be provided to the Tearsheet component by including an `aiLabel` property on it and providing the carbon AILabel component as its own custom component.',
        source: {
          language: 'jsx',
          code: `
<SidePanel
  {...args}
  aiLabel={
    // carbon AILabel component
    <AILabel
      className="ai-label-container"
      autoAlign={false}
      align="bottom-right"
    >
      <AILabelContent>... ...</AILabelContent>
    </AILabel>
  }
>
  ...
</SidePanel>
                `,
        },
      },
    ]}
  />
);

export default DocsPage;
