/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { generate, types as t } from '@carbon/scss-generator';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const { surfaces } = require('../lib/index.js');
const outputDirectory = path.resolve(__dirname, '../scss/generated');
const outputFile = path.join(outputDirectory, '_surfaces.scss');

// Not really necessary, I'll revisit this later
const banner = ` Code generated by @carbon/motion. DO NOT EDIT.

 Copyright IBM Corp. 2026

 This source code is licensed under the Apache-2.0 license found in the
 LICENSE file in the root directory of this source tree.
`;

// Use Sass-style names in the generated map.
function toKebabCase(value) {
  return value.replace(/[A-Z]/g, (character) => `-${character.toLowerCase()}`);
}

// Convert each TypeScript value into the matching Sass value.
function toSassValue(value) {
  if (Array.isArray(value)) {
    return t.SassList(value.map(toSassValue));
  }

  if (typeof value === 'object' && value !== null) {
    return t.SassMap(
      Object.entries(value).map(([key, item]) =>
        t.SassMapProperty(t.Identifier(toKebabCase(key)), toSassValue(item))
      )
    );
  }

  if (typeof value === 'boolean') {
    return t.SassBoolean(value);
  }

  if (typeof value === 'number') {
    return t.SassNumber(value);
  }

  return t.SassString(value);
}

// Generate Sass from the shared TypeScript surface definitions.
const stylesheet = t.StyleSheet([
  t.Comment(banner),
  t.Newline(),
  t.Assignment({
    id: t.Identifier('surfaces'),
    init: toSassValue(surfaces),
  }),
]);
const { code } = generate(stylesheet);

await mkdir(outputDirectory, { recursive: true });
await writeFile(outputFile, await code);
