/**
 * Copyright IBM Corp. 2018, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

const path = require('path');
const virtual = require('./plugins/virtual');

const BANNER = `/**
 * Copyright IBM Corp. 2016, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * Code generated by @carbon/icon-build-helpers. DO NOT EDIT.
 */`;

async function builder(metadata, { output }) {
  const { build: tsdown } = await import('tsdown');
  const modules = metadata.icons.flatMap((icon) => {
    return icon.output.map((size) => {
      const source = `export default ${JSON.stringify(size.descriptor)};`;
      return {
        source,
        filepath: size.filepath,
        moduleName: size.moduleName,
      };
    });
  });

  const files = {
    'index.js': `${BANNER}\n\n`,
  };
  const input = {
    'index.js': 'index.js',
  };

  for (const m of modules) {
    files[m.filepath] = m.source;
    input[m.filepath] = m.filepath;
    files['index.js'] +=
      `\nexport { default as ${m.moduleName} } from '${m.filepath}';`;
  }

  const bundles = [
    {
      directory: path.join(output, 'es'),
      format: 'esm',
    },
    {
      directory: path.join(output, 'lib'),
      format: 'commonjs',
    },
  ];

  for (const { directory, format } of bundles) {
    await tsdown({
      clean: false,
      dts: false,
      entry: input,
      failOnWarn: false,
      format: format === 'commonjs' ? 'cjs' : 'esm',
      inputOptions(inputOptions) {
        const options = { ...inputOptions };
        if ('define' in options) {
          delete options.define;
        }
        if ('inject' in options) {
          delete options.inject;
        }
        options.plugins = [...(options.plugins || []), virtual(files)];
        return options;
      },
      outDir: directory,
      outputOptions(options) {
        return {
          ...options,
          banner: BANNER,
          entryFileNames: '[name]',
          exports: 'auto',
        };
      },
      report: false,
      target: 'es2022',
    });
  }

  await tsdown({
    clean: false,
    dts: false,
    entry: {
      index: 'index.js',
    },
    failOnWarn: false,
    format: 'iife',
    globalName: 'CarbonIcons',
    inputOptions(inputOptions) {
      const options = { ...inputOptions };
      if ('define' in options) {
        delete options.define;
      }
      if ('inject' in options) {
        delete options.inject;
      }
      options.plugins = [...(options.plugins || []), virtual(files)];
      return options;
    },
    outDir: path.join(output, 'umd'),
    outputOptions(options) {
      return {
        ...options,
        banner: BANNER,
        entryFileNames: '[name].js',
      };
    },
    report: false,
    target: 'es2022',
  });
}

module.exports = builder;
