/**
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

/**
 * Format: carbon/js-themes
 *
 * Replicates the output of `tasks/builders/dtcg-js-themes.js`.
 *
 * Receives all tokens for ONE theme and emits two files (via SD's
 * `files` array):
 *   - `<themeName>.js`   — ES module with `export const camelName = value;`
 *   - `<themeName>.d.ts` — companion TypeScript declarations
 *
 * Token names arrive as kebab-case from SD and are converted to camelCase.
 *
 * Expected SD config (one platform entry per theme):
 *
 *   platforms: {
 *     'js/themes/white': {
 *       files: [
 *         {
 *           destination: 'js/generated/themes/white.js',
 *           format: 'carbon/js-themes',
 *           options: { themeName: 'white', output: 'js' },
 *         },
 *         {
 *           destination: 'js/generated/themes/white.d.ts',
 *           format: 'carbon/js-themes',
 *           options: { themeName: 'white', output: 'dts' },
 *         },
 *       ]
 *     }
 *   }
 */

// Banner matches dtcg-js-themes.js exactly: year 2025, no trailing '//'.
const FILE_BANNER = `// Code generated by @carbon/themes. DO NOT EDIT.
//
// Copyright IBM Corp. 2018, 2025
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.
`;

/**
 * Convert kebab-case to camelCase.
 * @param {string} str
 * @returns {string}
 */
function kebabToCamel(str) {
  return str.replace(/-([a-z0-9])/g, (_, ch) => ch.toUpperCase());
}

/**
 * Serialize a JS value to a source-code string.
 * Strings get single-quoted; everything else uses JSON.
 * @param {*} value
 * @returns {string}
 */
function toSource(value) {
  if (typeof value === 'string') {
    return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
  }
  return JSON.stringify(value);
}

/**
 * @param {{ dictionary: import('style-dictionary').Dictionary, options: object }} args
 * @returns {string}
 */
function carbonJsThemesFormat({ dictionary, options }) {
  const outputMode = options?.output ?? 'js'; // 'js' | 'dts'

  const lines = [FILE_BANNER];

  // Preserve JSON insertion order — allTokens is already in walk order from
  // buildThemeTokens(), matching convertDTCGToTheme. color-scheme lands first
  // naturally because the preprocessor injects it before the token tree walk.
  const sorted = dictionary.allTokens;

  for (const token of sorted) {
    const camelName = kebabToCamel(token.name);
    // SD v5 may store the resolved alias as a full token node object in
    // token.value when the alias points to a sibling token. Unwrap it.
    let value = token.value ?? token.$value;
    if (value !== null && typeof value === 'object' && '$value' in value) {
      value = value.$value;
    }
    const tsType = typeof value === 'string' ? 'string' : 'number';

    if (outputMode === 'js') {
      lines.push(`export const ${camelName} = ${toSource(value)};`);
    } else {
      lines.push(`export declare const ${camelName}: ${tsType};`);
    }
  }

  return lines.join('\n') + '\n';
}

module.exports = {
  name: 'carbon/js-themes',
  format: carbonJsThemesFormat,
};
