/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

/**
 * The format does not actually use the SD `dictionary` — it reads the token
 * list from the Carbon JS metadata directly, matching the original builder.
 * This is intentional: _tokens.scss is a mapping layer, not derived from the
 * token values.
 */

const { types: t } = require('@carbon/scss-generator');
const { generate } = require('@carbon/scss-generator');
const { group } = require('../../src/tokens');

const FILE_BANNER = `// Code generated by @carbon/themes. DO NOT EDIT.
//
// Copyright IBM Corp. 2018, 2023
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.
//
`;

/**
 * @returns {Promise<string>}
 */
async function carbonScssTokensFormat() {
  const tokens = group.getTokens();

  const variables = tokens.flatMap((token) => {
    const id = token.name;
    return [
      t.Newline(),
      t.Comment(`/ The CSS Custom Property for the \`${id}\` token`),
      t.Assignment({
        id: t.Identifier(id),
        init: t.SassFunctionCall({
          id: t.Identifier('_get'),
          params: [t.SassString(id)],
        }),
        default: true,
      }),
    ];
  });

  const stylesheet = t.StyleSheet([
    t.SassModule('sass:map'),
    t.SassModule('../config'),
    t.SassModule('../theme'),
    t.Newline(),
    t.Comment('/ Internal helper for generating CSS Custom Properties'),
    t.SassFunction({
      id: t.Identifier('_get'),
      params: [t.Identifier('token')],
      body: t.BlockStatement([
        t.IfStatement({
          test: t.LogicalExpression({
            left: t.SassValue('config.$use-fallback-value'),
            operator: '==',
            right: t.SassBoolean(false),
          }),
          consequent: t.BlockStatement([
            t.AtReturn(t.SassValue('var(--#{config.$prefix}-#{$token})')),
          ]),
          alternate: t.BlockStatement([
            t.AtReturn(
              t.SassValue(
                'var(--#{config.$prefix}-#{$token}, #{theme.get($token)})'
              )
            ),
          ]),
        }),
      ]),
    }),
    ...variables,
  ]);

  const { code } = generate(stylesheet);
  return FILE_BANNER + '\n' + (await code);
}

module.exports = {
  name: 'carbon/scss-tokens',
  format: carbonScssTokensFormat,
};
