/**
 * Copyright IBM Corp. 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

/**
 *
 *
 * Each theme (white, g10, g90, g100) is expected to be a separate SD
 * *platform* build run.  This format receives all tokens for ONE theme and
 * emits the Sass map variable for that theme plus the utilities.merge call
 * that folds in layout spacing and type tokens.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * NOTE ON MULTI-THEME FILES
 * ─────────────────────────────────────────────────────────────────────────────
 *  The recommended approach:  run all four platforms, collect their individual
 * strings, and concatenate them in sd.config.js using a custom action.
 * A simpler alternative (and the one wired up in sd.config.js) is to use SD's
 * `buildAllPlatforms()` with four platforms that each write to a *separate*
 * file, then a post-build step (`buildAllPlatforms` custom action) concatenates
 * them.  Both patterns are documented in style-dictionary/README.md.
 */

const FILE_BANNER = `// Code generated by @carbon/themes. DO NOT EDIT.
//
// Copyright IBM Corp. 2018, 2023
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.
//
`;

const SCSS_IMPORTS = `@use 'sass:map';
@use 'sass:string';
@use '@carbon/layout';
@use '@carbon/type';
@use '../utilities';
`;

/**
 * Serialize a CSS color value to a Sass literal.
 *
 * - Hex colors   → bare hex       (e.g.  #ffffff)
 * - rgba()       → bare function  (e.g.  rgba(141, 141, 141, 0.5))
 * - Strings      → string.unquote("…")
 * - Numbers      → bare number
 *
 * @param {string|number} value
 * @returns {string}  Sass source fragment
 */
function toSassLiteral(value) {
  if (typeof value === 'number') {
    return String(value);
  }
  if (typeof value !== 'string') {
    return JSON.stringify(value);
  }
  if (value.startsWith('#')) {
    return value;
  }
  if (
    value.startsWith('rgb') ||
    value.endsWith('px') ||
    value.endsWith('em') ||
    value.endsWith('%') ||
    value.endsWith('vw') ||
    value.endsWith('vh') ||
    value === '0'
  ) {
    return value;
  }
  // Plain string (e.g. 'light', 'dark') → Sass unquote with single quotes,
  // matching t.SassValue("string.unquote('...')") in the old builder.
  return `string.unquote('${value}')`;
}

/**
 * @param {{ dictionary: import('style-dictionary').Dictionary, options: object, file: object }} args
 * @returns {string}
 */
function carbonScssThemesFormat({ dictionary, options, file }) {
  const themeName = options?.themeName ?? file?.options?.themeName ?? 'unknown';

  // Sort alphabetically — matches dtcg-themes.js which calls .sort(([a],[b])=>a.localeCompare(b))
  // color-scheme lands at its natural alpha position ('c' section).
  const sorted = [...dictionary.allTokens].sort((a, b) =>
    a.name.localeCompare(b.name)
  );

  const entries = sorted
    .map((token) => {
      const name = token.name;
      // SD v5 may store the post-alias value as a full token node object in
      // token.value when an alias points to a sibling token. Unwrap it.
      let value = token.value ?? token.$value;
      if (value !== null && typeof value === 'object' && '$value' in value) {
        value = value.$value;
      }
      // Unquoted key — matches t.SassMapProperty(t.Identifier(token), ...) in old builder
      return `  ${name}: ${toSassLiteral(value)},`;
    })
    .join('\n');

  return (
    FILE_BANNER +
    '\n' +
    SCSS_IMPORTS +
    '\n' +
    `$${themeName}: (\n${entries}\n) !default;\n` +
    `$${themeName}: utilities.merge(\n` +
    `  $${themeName},\n` +
    `  layout.$spacing,\n` +
    `  layout.$fluid-spacing,\n` +
    `  type.$tokens\n` +
    `);\n`
  );
}

module.exports = {
  name: 'carbon/scss-themes',
  format: carbonScssThemesFormat,
};
