/**
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

/**
 * Format: carbon/scss-tokens
 *
 * Replicates the output of `tasks/builders/dtcg-tokens.js`.
 *
 * Emits a Sass file that:
 *   1. `@use`s sass:map, config, and theme modules.
 *   2. Defines an internal `_get($token)` helper that returns either a bare
 *      CSS custom property or one with a fallback value depending on
 *      `config.$use-fallback-value`.
 *   3. For every token in the Carbon token set, emits a `$token-name: _get('token-name') !default;`
 *      Sass variable.
 *
 * Token names come from the JS metadata (`src/tokens`), not from the DTCG
 * files — this matches the existing builder exactly.
 *
 * Expected SD config:
 *
 *   platforms: {
 *     'scss/tokens': {
 *       files: [{
 *         destination: 'scss/generated/_tokens.scss',
 *         format: 'carbon/scss-tokens',
 *       }]
 *     }
 *   }
 *
 * The format does not actually use the SD `dictionary` — it reads the token
 * list from the Carbon JS metadata directly, matching the original builder.
 * This is intentional: _tokens.scss is a mapping layer, not derived from the
 * token values.
 */

// Use the same @carbon/scss-generator AST that the old dtcg-tokens.js uses.
// This ensures long token names are line-wrapped identically (the AST formatter
// auto-wraps function calls that exceed ~80 chars, e.g. _get('ai-skeleton-...'))
const { types: t } = require('@carbon/scss-generator');
const { generate } = require('@carbon/scss-generator');
const { group } = require('../../src/tokens');

// Inline the same banner that shared.js produces — avoids a dependency on
// shared.js (which requires ../../lib, not yet built when build:js-tokens runs).
const SCSS_FILE_BANNER =
  t.Comment(` Code generated by @carbon/themes. DO NOT EDIT.

 Copyright IBM Corp. 2018, 2023

 This source code is licensed under the Apache-2.0 license found in the
 LICENSE file in the root directory of this source tree.
`);

/**
 * @returns {Promise<string>}
 */
async function carbonScssTokensFormat() {
  const tokens = group.getTokens();

  const variables = tokens.flatMap((token) => {
    const id = token.name;
    return [
      t.Newline(),
      t.Comment(`/ The CSS Custom Property for the \`${id}\` token`),
      t.Assignment({
        id: t.Identifier(id),
        init: t.SassFunctionCall({
          id: t.Identifier('_get'),
          params: [t.SassString(id)],
        }),
        default: true,
      }),
    ];
  });

  const stylesheet = t.StyleSheet([
    SCSS_FILE_BANNER,
    t.Newline(),
    t.SassModule('sass:map'),
    t.SassModule('../config'),
    t.SassModule('../theme'),
    t.Newline(),
    t.Comment('/ Internal helper for generating CSS Custom Properties'),
    t.SassFunction({
      id: t.Identifier('_get'),
      params: [t.Identifier('token')],
      body: t.BlockStatement([
        t.IfStatement({
          test: t.LogicalExpression({
            left: t.SassValue('config.$use-fallback-value'),
            operator: '==',
            right: t.SassBoolean(false),
          }),
          consequent: t.BlockStatement([
            t.AtReturn(t.SassValue('var(--#{config.$prefix}-#{$token})')),
          ]),
          alternate: t.BlockStatement([
            t.AtReturn(
              t.SassValue(
                'var(--#{config.$prefix}-#{$token}, #{theme.get($token)})'
              )
            ),
          ]),
        }),
      ]),
    }),
    ...variables,
  ]);

  const { code } = generate(stylesheet);
  return code;
}

module.exports = {
  name: 'carbon/scss-tokens',
  format: carbonScssTokensFormat,
};
