/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import styles from './page-header.scss?lit';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';

/**
 * Page header content.
 * @element cds-page-header-content
 */
@customElement(`${prefix}-page-header-content`)
class CDSPageHeaderContent extends LitElement {
  /**
   * `true` if there is body content.
   */
  private _hasBody = false;

  /**
   * `true` if there are contextual actions
   */
  private _hasContextualActions = false;

  /**
   * Handles `slotchange` event.
   */
  protected _handleSlotChange({ target }: Event) {
    this._hasBody = Boolean((target as HTMLSlotElement).assignedNodes());
    this.requestUpdate();
  }

  /**
   * Handles `slotchange` event.
   */
  protected _handleContextualActionsSlotChange({ target }: Event) {
    this._hasContextualActions = Boolean(
      (target as HTMLSlotElement).assignedNodes()
    );
    if (this._hasContextualActions) {
      this.setAttribute('contextual-actions', 'true');
    } else {
      this.removeAttribute('contextual-actions');
    }
    this.requestUpdate();
  }

  @property()
  title = '';

  @property()
  subtitle = '';

  render() {
    const {
      title,
      subtitle,
      _hasBody: hasBody,
      _handleSlotChange: handleSlotChange,
      _handleContextualActionsSlotChange: handleContextualActionsSlotChange,
    } = this;
    return html` <div class="${prefix}--css-grid">
      <div
        class="${prefix}--sm:col-span-4 ${prefix}--md:col-span-8 ${prefix}--lg:col-span-16 ${prefix}--css-grid-column">
        <div class="${prefix}--page-header__content__title-wrapper">
          <div class="${prefix}--page-header__content__start">
            <div class="${prefix}--page-header__content__title-container">
              <slot name="icon"></slot>
              <h4 class="${prefix}--page-header__content__title">${title}</h4>
            </div>
            <slot
              name="contextual-actions"
              @slotchange=${handleContextualActionsSlotChange}></slot>
          </div>
          <div class="${prefix}--page-header__content__end">
            <slot name="page-actions"></slot>
          </div>
        </div>
        ${subtitle &&
        html`<h3 class="${prefix}--page-header__content__sub-title">
          ${subtitle}
        </h3>`}
        <div class="${prefix}--page-header__content__body" ?hidden=${!hasBody}>
          <slot @slotchange=${handleSlotChange}></slot>
        </div>
      </div>
    </div>`;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom Vite loader
}

export default CDSPageHeaderContent;
