/**
 * @license
 *
 * Copyright IBM Corp. 2019, 2023
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { classMap } from 'lit/directives/class-map.js';
import { LitElement, html } from 'lit';
import { property, customElement } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import styles from './breadcrumb.scss';

/**
 * Breadcrumb.
 *
 * @element cds-breadcrumb
 */
@customElement(`${prefix}-breadcrumb`)
class BXBreadcrumb extends LitElement {
  /**
   * Optional prop to omit the trailing slash for the breadcrumbs
   */
  @property({ type: Boolean, reflect: true, attribute: 'no-trailing-slash' })
  noTrailingSlash = false;

  connectedCallback() {
    if (!this.hasAttribute('role')) {
      this.setAttribute('role', 'nav');
    }
    super.connectedCallback();
  }

  render() {
    const classes = classMap({
      [`${prefix}--breadcrumb`]: true,
      [`${prefix}--breadcrumb--no-trailing-slash`]: this.noTrailingSlash,
    });
    return html`
      <ol class="${classes}">
        <slot></slot>
      </ol>
    `;
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default BXBreadcrumb;
