/**
 * Copyright IBM Corp. 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { StoryDocsPage } from '../../global/js/utils/StoryDocsPage';

import * as stories from './Tearsheet.stories';

const DocsPage = () => (
  <StoryDocsPage
    blocks={[
      {
        story: stories.tearsheet,
      },
      {
        story: stories.withNavigation,
      },
      {
        story: stories.withInfluencer,
      },
      {
        story: stories.ReturnFocusToOpenButton,
      },
      {
        story: stories.firstElementDisabled,
      },
      {
        story: stories.firstElementReadOnly,
      },
      {
        story: stories.fullyLoaded,
      },
      {
        story: stories.stacked,
      },
      {
        story: stories.stackedMixedSizes,
      },
      {
        title: 'With AI Label',
        description:
          'An AI Label is intended for any scenario where something is being generated by AI to reinforce AI transparency, accountability, and explainability at the UI level. A Carbon AI Label can be provided to the Tearsheet component by including an `decorator` property on it and providing the carbon AILabel component as its own custom component.<br/> The `decorator` is versatile and can also be used to render other components.',
        source: {
          language: 'html',
          code: `
<Tearsheet
  {...args}
  decorator={
    // carbon AILabel component
    <AILabel
      className="ai-label-container"
      autoAlign={false}
      align="bottom-right"
    >
      <AILabelContent>... ...</AILabelContent>
    </AILabel>
  }
>
  ...
</Tearsheet>
          `,
        },
      },
    ]}
  />
);

export default DocsPage;
