/**
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { GuidebannerElementButton } from './GuidebannerElementButton';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  GuidebannerElementButton,
  'https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/-v11--IBM-Products-%E2%80%93-Carbon-Design-System?node-id=17606%3A27272',
  {
    props: {
      children: figma.textContent('Button'),
    },
    example: (props) => (
      <GuidebannerElementButton>{props.children}</GuidebannerElementButton>
    ),
  }
);
