/**
 * Copyright IBM Corp. 2025
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { Guidebanner } from './Guidebanner';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Guidebanner,
  'https://www.figma.com/design/0F9dKH2abAd7gSfvnacfWf/-v11--IBM-Products-%E2%80%93-Carbon-Design-System?node-id=16728%3A642275',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      collapsible: figma.enum('Type', {
        Collapsable: true,
      }),
      title: figma.string('Header text'),
      children: figma.children('_Insight'),
      open: figma.boolean('Expanded'),
    },
    example: (props) => (
      <Guidebanner
        collapsible={props.collapsible}
        title={props.title}
        open={props.open}
      >
        {props.children}
      </Guidebanner>
    ),
  }
);
