coverage:
  status:
    project:
      components:
        target: auto # every new commit must maintain or raise the overall code coverage
        threshold: 1%
        paths:
          - src/components/
