// @ts-nocheck
import React from 'react';
import { ContentSwitcher } from './ContentSwitcher';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ContentSwitcher,
  'https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?node-id=10151-402486&t=LoXqbMLZkoMgbrAS-4',
  {
    props: {
      type: figma.enum('Type', {
        Default: 'default',
        'Icon only': 'icon-only',
      }),
      size: figma.enum('Size', {
        Large: 'large',
        Medium: 'medium',
        Small: 'small',
      }),
      disabled: figma.boolean('Disabled'),
    },
    example: () => <ContentSwitcher />,
  }
);
