/**
 * @license
 *
 * Copyright IBM Corp. 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { prefix } from '../../globals/settings';
import styles from './menu-item.scss?lit';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
/**
 * Menu Item.
 *
 * @element cds-menu-item-divider
 */
@customElement(`${prefix}-menu-item-divider`)
class CDSmenuItemDivider extends LitElement {
  render() {
    return html`
      <li class="${prefix}--menu-item-divider" role="separator"></li>
    `;
  }
  static styles = styles; // `styles` here is a `CSSResult` generated by custom Vite loader
}
export default CDSmenuItemDivider;
