/**
 * @license
 *
 * Copyright IBM Corp. 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { LitElement, html } from 'lit';
import { property } from 'lit/decorators.js';
import { prefix } from '../../globals/settings';
import styles from './menu-item.scss?lit';
import { carbonElement as customElement } from '../../globals/decorators/carbon-element';
import { classMap } from 'lit/directives/class-map.js';
/**
 * Menu Item.
 *
 * @element cds-menu-item
 */
@customElement(`${prefix}-menu-item-selectable`)
class CDSmenuItemSelectable extends LitElement {
  /**
   * Label for the menu item selectable.
   */
  @property({ type: String })
  label;
  /**
   * Whether the menu item is selected or not.
   */
  @property({ type: Boolean })
  selected = false;

  /**
   * Provide an optional function to be called when the selection state changes.
   */
  onChange?;

  _handleClick = (e) => {
    this.selected = !this.selected;
    if (this.onChange) {
      this.onChange(e);
    }
  };
  render() {
    const { label, selected, _handleClick: handleClick } = this;
    let checked = true;
    return html`
      <cds-menu-item
        label="${label}"
        aria-checked="${selected}"
        renderIcon="${selected ? 'checkMark' : undefined}"
        @click="${handleClick}"></cds-menu-item>
    `;
  }
  static styles = styles; // `styles` here is a `CSSResult` generated by custom Vite loader
}
export default CDSmenuItemSelectable;
