/**
 * Copyright IBM Corp. 2018, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

/**
 * Custom Style Dictionary format for @carbon/colors.
 *
 * Generates js/generated/colors.js and js/generated/colors.d.ts from the
 * DTCG token source. The output reproduces the exact public API of the
 * existing hand-authored colors.ts:
 *
 *   - Individual hex exports:  export const blue60 = '#0f62fe';
 *   - Aliases:                 export const black100 = black;
 *                              export const white0 = white;
 *   - Swatch group objects:    export const blue = { 10: blue10, ... };
 *   - Hover group objects:     export const blueHover = { 10: blue10Hover, ... };
 *   - Aggregate maps:          export const colors = { ... };
 *                              export const hoverColors = { ... };
 */

const FILE_BANNER = `// Code generated by @carbon/colors. DO NOT EDIT.
//
// Copyright IBM Corp. 2018, 2026
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.
`;

// All swatch families in source order
const FAMILIES = [
  'yellow',
  'orange',
  'red',
  'magenta',
  'purple',
  'blue',
  'cyan',
  'teal',
  'green',
  'coolGray',
  'gray',
  'warmGray',
];

function isHover(grade) {
  return grade === 'Hover' || grade.endsWith('Hover');
}

/**
 * @param {{ dictionary: import('style-dictionary').Dictionary, options: { output?: 'js' | 'dts' } }} args
 * @returns {string}
 */
function carbonJsColorsFormat({ dictionary, options }) {
  const output = options?.output ?? 'js';
  const tokens = dictionary.allTokens;

  // Index tokens by path
  const byFamily = {};
  const standalone = {}; // black, white, blackHover, whiteHover

  for (const token of tokens) {
    // SD v5 DTCG: literal $value stays in token.$value; token.value is only
    // set for alias-resolved tokens. Read both, prefer token.$value.
    const value = token.$value ?? token.value;
    if (token.path.length === 1) {
      standalone[token.path[0]] = value;
    } else if (token.path.length === 2) {
      const [family, grade] = token.path;
      if (!byFamily[family]) byFamily[family] = {};
      byFamily[family][grade] = value;
    }
  }

  if (output === 'dts') {
    return generateDts(byFamily);
  }
  return generateJs(standalone, byFamily);
}

function generateJs(standalone, byFamily) {
  const lines = [FILE_BANNER];

  // ── black / white standalones ───────────────────────────────────────────────
  lines.push(`export const black = '${standalone['black'] ?? '#000000'}';`);
  lines.push(`export const black100 = black;`);
  lines.push(
    `export const blackHover = '${standalone['blackHover'] ?? '#212121'}';`
  );
  lines.push('');
  lines.push(`export const white = '${standalone['white'] ?? '#ffffff'}';`);
  lines.push(`export const white0 = white;`);
  lines.push(
    `export const whiteHover = '${standalone['whiteHover'] ?? '#e8e8e8'}';`
  );
  lines.push('');

  // ── Per-family: solid grades, group object, hover grades, hover group ───────
  for (const family of FAMILIES) {
    const grades = byFamily[family] ?? {};

    const solidGrades = Object.keys(grades)
      .filter((g) => !isHover(g))
      .sort((a, b) => Number(a) - Number(b));

    const hoverGrades = Object.keys(grades)
      .filter((g) => isHover(g) && g !== 'Hover')
      .sort(
        (a, b) =>
          Number(a.replace('Hover', '')) - Number(b.replace('Hover', ''))
      );

    for (const grade of solidGrades) {
      lines.push(`export const ${family}${grade} = '${grades[grade]}';`);
    }
    lines.push(`export const ${family} = {`);
    for (const grade of solidGrades) {
      lines.push(`  ${grade}: ${family}${grade},`);
    }
    lines.push(`};`);
    lines.push('');

    for (const grade of hoverGrades) {
      lines.push(`export const ${family}${grade} = '${grades[grade]}';`);
    }
    lines.push(`export const ${family}Hover = {`);
    for (const grade of hoverGrades) {
      lines.push(`  ${grade.replace('Hover', '')}: ${family}${grade},`);
    }
    lines.push(`};`);
    lines.push('');
  }

  // ── colors aggregate map ────────────────────────────────────────────────────
  lines.push(`export const colors = {`);
  lines.push(`  black: { 100: black },`);
  for (const family of FAMILIES) {
    const grades = byFamily[family] ?? {};
    const solidGrades = Object.keys(grades)
      .filter((g) => !isHover(g))
      .sort((a, b) => Number(a) - Number(b));
    lines.push(`  ${family}: {`);
    for (const grade of solidGrades) {
      lines.push(`    ${grade}: ${family}${grade},`);
    }
    lines.push(`  },`);
  }
  lines.push(`  white: { 0: white },`);
  lines.push(`};`);
  lines.push('');

  // ── hoverColors aggregate map ───────────────────────────────────────────────
  lines.push(`export const hoverColors = {`);
  lines.push(`  blackHover,`);
  for (const family of FAMILIES) {
    lines.push(`  ${family}Hover,`);
  }
  lines.push(`  whiteHover,`);
  lines.push(`};`);

  return lines.join('\n') + '\n';
}

function generateDts(byFamily) {
  const lines = [FILE_BANNER];

  lines.push(`export declare const black: string;`);
  lines.push(`export declare const black100: string;`);
  lines.push(`export declare const blackHover: string;`);
  lines.push(`export declare const white: string;`);
  lines.push(`export declare const white0: string;`);
  lines.push(`export declare const whiteHover: string;`);
  lines.push('');

  for (const family of FAMILIES) {
    const grades = byFamily[family] ?? {};
    const solidGrades = Object.keys(grades)
      .filter((g) => !isHover(g))
      .sort((a, b) => Number(a) - Number(b));
    const hoverGrades = Object.keys(grades)
      .filter((g) => isHover(g) && g !== 'Hover')
      .sort(
        (a, b) =>
          Number(a.replace('Hover', '')) - Number(b.replace('Hover', ''))
      );

    for (const grade of solidGrades) {
      lines.push(`export declare const ${family}${grade}: string;`);
    }
    lines.push(`export declare const ${family}: Record<number, string>;`);
    lines.push('');

    for (const grade of hoverGrades) {
      lines.push(`export declare const ${family}${grade}: string;`);
    }
    lines.push(`export declare const ${family}Hover: Record<number, string>;`);
    lines.push('');
  }

  lines.push(`export type ColorScale = Record<number, string>;`);
  lines.push(`export type ColorGroup = Record<string, ColorScale>;`);
  lines.push(
    `export type HoverColorGroup = Record<string, string | ColorScale>;`
  );
  lines.push('');
  lines.push(`export declare const colors: ColorGroup;`);
  lines.push(`export declare const hoverColors: HoverColorGroup;`);

  return lines.join('\n') + '\n';
}

module.exports = {
  name: 'carbon/js-colors',
  format: carbonJsColorsFormat,
};
