/**
 * Copyright IBM Corp. 2018, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

/**
 * Custom Style Dictionary format for @carbon/colors.
 *
 * Reproduces the exact structure of the hand-authored index.scss:
 *   - $black and $white standalone variables
 *   - $family-grade individual variables (e.g. $blue-10, $cool-gray-50)
 *   - hover variants (e.g. $blue-10-hover, $black-hover)
 *   - $colors Sass map (solid grades only, no hover)
 *
 * The token path in the DTCG JSON is [family, grade], e.g. ['blue', '60'].
 * Top-level tokens (black, white, blackHover, whiteHover) have path length 1.
 */

const FILE_BANNER = `// Code generated by @carbon/colors. DO NOT EDIT.
//
// Copyright IBM Corp. 2018, 2026
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.
//
`;

// camelCase family → kebab-case SCSS variable prefix
// e.g. coolGray → cool-gray, warmGray → warm-gray
function toKebab(family) {
  return family.replace(/([A-Z])/g, (m) => `-${m.toLowerCase()}`);
}

// Returns true if this grade key is a hover variant
function isHover(grade) {
  return grade === 'Hover' || grade.endsWith('Hover');
}

// All swatch families in source order (matches colors.ts)
const FAMILIES = [
  'yellow',
  'orange',
  'red',
  'magenta',
  'purple',
  'blue',
  'cyan',
  'teal',
  'green',
  'coolGray',
  'gray',
  'warmGray',
];

/**
 * @param {{ dictionary: import('style-dictionary').Dictionary }} args
 * @returns {string}
 */
function carbonScssColorsFormat({ dictionary }) {
  const tokens = dictionary.allTokens;

  // Index tokens by path for easy lookup
  // path[0] = family (or standalone like 'black'), path[1] = grade
  const byFamily = {};
  const standalone = {}; // black, white, blackHover, whiteHover

  for (const token of tokens) {
    // SD v5 DTCG: literal $value stays in token.$value; token.value is only
    // set for alias-resolved tokens. Read both, prefer token.$value.
    const value = token.$value ?? token.value;
    if (token.path.length === 1) {
      standalone[token.path[0]] = value;
    } else if (token.path.length === 2) {
      const [family, grade] = token.path;
      if (!byFamily[family]) byFamily[family] = {};
      byFamily[family][grade] = value;
    }
  }

  const lines = [FILE_BANNER];

  // ── Standalone: $black, $white ──────────────────────────────────────────────
  lines.push(`$black: ${standalone['black'] ?? '#000000'} !default;`);
  lines.push(`$white: ${standalone['white'] ?? '#ffffff'} !default;`);
  lines.push('');

  // ── black-100 alias + family-grade variables ────────────────────────────────
  lines.push(`$black-100: ${standalone['black'] ?? '#000000'} !default;`);

  for (const family of FAMILIES) {
    const grades = byFamily[family] ?? {};
    const kebab = toKebab(family);

    // Solid grades first (10–100), in ascending order
    const solidGrades = Object.keys(grades)
      .filter((g) => !isHover(g))
      .sort((a, b) => Number(a) - Number(b));

    for (const grade of solidGrades) {
      lines.push(`$${kebab}-${grade}: ${grades[grade]} !default;`);
    }
  }

  // white-0 alias
  lines.push(`$white-0: ${standalone['white'] ?? '#ffffff'} !default;`);
  lines.push('');

  // ── Hover variables ─────────────────────────────────────────────────────────
  lines.push(
    `$white-hover: ${standalone['whiteHover'] ?? '#e8e8e8'} !default;`
  );
  lines.push(
    `$black-hover: ${standalone['blackHover'] ?? '#212121'} !default;`
  );

  for (const family of FAMILIES) {
    const grades = byFamily[family] ?? {};
    const kebab = toKebab(family);

    // Hover grades in ascending numeric order
    const hoverGrades = Object.keys(grades)
      .filter((g) => isHover(g) && g !== 'Hover')
      .sort(
        (a, b) =>
          Number(a.replace('Hover', '')) - Number(b.replace('Hover', ''))
      );

    for (const grade of hoverGrades) {
      const numericPart = grade.replace('Hover', '');
      lines.push(`$${kebab}-${numericPart}-hover: ${grades[grade]} !default;`);
    }
  }

  lines.push('');

  // ── $colors map (solid grades only) ─────────────────────────────────────────
  lines.push(`/// Colors from the IBM Design Language`);
  lines.push(`/// @access public`);
  lines.push(`/// @group @carbon/colors`);
  lines.push(`$colors: (`);

  // black entry
  lines.push(`  black: (`);
  lines.push(`    100: ${standalone['black'] ?? '#000000'},`);
  lines.push(`  ),`);

  for (const family of FAMILIES) {
    const grades = byFamily[family] ?? {};
    const kebab = toKebab(family);

    const solidGrades = Object.keys(grades)
      .filter((g) => !isHover(g))
      .sort((a, b) => Number(a) - Number(b));

    if (solidGrades.length === 0) continue;

    lines.push(`  ${kebab}: (`);
    for (const grade of solidGrades) {
      lines.push(`    ${grade}: ${grades[grade]},`);
    }
    lines.push(`  ),`);
  }

  // white entry
  lines.push(`  white: (`);
  lines.push(`    0: ${standalone['white'] ?? '#ffffff'},`);
  lines.push(`  ),`);

  lines.push(`) !default;`);

  return lines.join('\n') + '\n';
}

module.exports = {
  name: 'carbon/scss-colors',
  format: carbonScssColorsFormat,
};
