/**
 * Copyright IBM Corp. 2024
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import React from 'react';
import { StoryDocsPage } from '../../global/js/utils/StoryDocsPage';

import * as stories from './ProductiveCard.stories';

const DocsPage = () => (
  <StoryDocsPage
    altGuidelinesHref="https://pages.github.ibm.com/carbon/ibm-products/components/card/productive-card/usage/"
    blocks={[
      {
        story: stories.Clickable,
      },
      {
        story: stories.ComplexBottomBar,
      },
      {
        story: stories.Default,
      },
      {
        story: stories.LabelOnly,
      },
      {
        story: stories.SupplementalBottomBar,
      },
      {
        story: stories.WithActionGhostButton,
      },
      {
        story: stories.WithButtonHref,
      },
      {
        story: stories.WithCaption,
      },
      {
        story: stories.WithLabel,
      },
      {
        story: stories.WithOverflow,
        description:
          'To include an overflow menu within the productive card, you should provide an array of objects. These will map to the overflow items. All supported props from `OverflowItem` will be passed through to the overflow menu items created via the `overflowActions` prop.',
      },
      {
        title: 'With AI label',
        description:
          'An AI Label is intended for any scenario where something is being generated by AI to reinforce AI transparency, accountability, and explainability at the UI level.',
        source: {
          language: 'html',
          code: `
          <ProductiveCard
  onClick={() => {}}
  onKeyDown={() => {}}
  primaryButtonText="Ghost button"
  decorator={<AILabel>...</AILabel> || true}
  title="Title"
>
  <React.Fragment key=".0">
    <div className="graph" />
    <p>
      Productive content text
    </p>
    <p>
      Productive content text
    </p>
  </React.Fragment>
</ProductiveCard>
          `,
        },
      },
      {
        description:
          'Clickable tiles only accept a boolean value of true for the decorator property.',
        source: {
          language: 'html',
          code: `
          <ProductiveCard
  onClick={() => {}}
  onKeyDown={() => {}}
  primaryButtonText="Ghost button"
  decorator={true}
  title="Title"
>
  <React.Fragment key=".0">
    <div className="graph" />
    <p>
      Productive content text
    </p>
    <p>
      Productive content text
    </p>
  </React.Fragment>
</ProductiveCard>
          `,
        },
      },
    ]}
  />
);

export default DocsPage;
