// import React from "react"
// import { RadioButtonGroup } from "./RadioButtonGroup"
// import figma from "@figma/code-connect"

// /**
//  * -- This file was auto-generated by `figma connect create` --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   RadioButtonGroup,
//   "https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?node-id=2927-28166&t=yFGI7EFVWv0vtqIk-4",
//   {
//     props: {
//       helpertext: figma.string("Helper text"),
//       warningtext: figma.string("Warning text"),
//       errortext: figma.string("Error text"),
//       helpermessage: figma.boolean("Helper message"),
//       labeltext: figma.string("Label text"),
//       state: figma.enum("State", {
//         Enabled: "enabled",
//         Invalid: "invalid",
//         "Read-only": "read-only",
//         Warning: "warning",
//       }),
//       horizontal: figma.boolean("Horizontal"),
//     },
//     example: (props) => <RadioButtonGroup />,
//   },
// )
