#!/usr/bin/env python3
"""Index CoForge OS artifact manifests as pointers (no payload copy).

Root: env COFORGE_OS, else packages/themes/src/dtcg/coforge/rag/root.txt

  python3 packages/themes/src/dtcg/coforge/scripts/build-rag-index.py
"""

from __future__ import annotations

import json
import os
from pathlib import Path

HERE = Path(__file__).resolve()
RAG_DIR = HERE.parents[1] / "rag"
OUT = RAG_DIR / "index.json"


def os_root() -> Path:
    env = os.environ.get("COFORGE_OS", "").strip()
    if env:
        return Path(env).expanduser().resolve()
    line = (RAG_DIR / "root.txt").read_text(encoding="utf-8").strip()
    return Path(line).expanduser().resolve()


def main() -> None:
    root = os_root()
    artifacts = root / "artifacts"
    if not artifacts.is_dir():
        raise SystemExit(f"CoForge OS artifacts missing: {artifacts}")

    rows = []
    for manifest in sorted(artifacts.rglob("manifest.json")):
        if "_templates" in manifest.parts:
            continue
        data = json.loads(manifest.read_text(encoding="utf-8"))
        rel_dir = str(manifest.parent.relative_to(root))
        payload = data.get("file") or ""
        rows.append(
            {
                "id": data.get("id"),
                "type": data.get("type"),
                "version": data.get("version"),
                "supersedes": data.get("supersedes"),
                "status": data.get("status"),
                "workstream": data.get("workstream"),
                "title": data.get("title"),
                "file": payload,
                "dir": rel_dir,
                "abs_dir": str(manifest.parent),
                "abs_file": str(manifest.parent / payload) if payload else None,
            }
        )

    superseded_dirs = set()
    for row in rows:
        sup = row.get("supersedes")
        if not sup:
            continue
        p = Path(str(sup))
        superseded_dirs.add(str(p).rstrip("/"))

    for row in rows:
        d = row["dir"].rstrip("/")
        row["current"] = d not in superseded_dirs and not any(
            d == s.rstrip("/") for s in superseded_dirs
        )

    payload = {
        "$comment": "Generated by scripts/build-rag-index.py. Pointers only. Do not copy CoForge OS into this repo.",
        "root": str(root),
        "count": len(rows),
        "artifacts": rows,
    }
    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    current = sum(1 for r in rows if r["current"])
    print(f"wrote {len(rows)} artifacts ({current} current) → {OUT}")


if __name__ == "__main__":
    main()
