/**
 * Copyright IBM Corp. 2018, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

/**
 * Emits `js/generated/tokens.{js,d.ts}` from the motion DTCG tokens.
 *
 * The format receives all resolved tokens (duration + easing) and produces:
 *   - V11 duration exports        (durationFast01, durationFast02, …)
 *   - V10 deprecated aliases      (fast01, fast02, …)
 *   - `easings` nested object     ({ standard: { productive, expressive }, … })
 *   - `unstable_tokens` array
 *
 * Two files are emitted by wiring this format into two SD `files` entries
 * that differ only in `options.output` ('js' | 'dts').
 */

const FILE_BANNER = `// Code generated by @carbon/motion. DO NOT EDIT.
//
// Copyright IBM Corp. 2018, 2026
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.
`;

/**
 * Convert kebab-case to camelCase.
 * @param {string} str
 * @returns {string}
 */
function kebabToCamel(str) {
  return str.replace(/-([a-z0-9])/gi, (_, ch) => ch.toUpperCase());
}

/**
 * Derive the V10 camelCase alias name from a V11 camelCase name.
 * e.g. 'durationFast01' → 'fast01'
 */
function toV10CamelName(v11Camel) {
  // Strip the leading 'duration' prefix and lowercase the first char.
  const withoutPrefix = v11Camel.slice('duration'.length);
  return withoutPrefix.charAt(0).toLowerCase() + withoutPrefix.slice(1);
}

/**
 * @param {{ dictionary: import('style-dictionary').Dictionary, options: object }} args
 * @returns {string}
 */
function carbonJsMotionTokensFormat({ dictionary, options }) {
  const outputMode = options?.output ?? 'js'; // 'js' | 'dts'

  // Build a lookup from kebab token name → resolved value
  const tokenMap = new Map(
    dictionary.allTokens.map((t) => [t.name, t.value ?? t.$value])
  );

  const lines = [FILE_BANNER];

  // ── Duration tokens (V11 canonical) ──────────────────────────────────────
  lines.push('// Duration tokens (V11)');
  const durationTokens = dictionary.allTokens.filter((t) =>
    t.name.startsWith('duration-')
  );
  const durationCamels = [];

  for (const token of durationTokens) {
    const camel = kebabToCamel(token.name);
    durationCamels.push(camel);
    const value = token.value ?? token.$value;
    const description = token.$description ?? token.description ?? '';

    if (description) {
      lines.push(`/** ${description} */`);
    }
    if (outputMode === 'js') {
      lines.push(`export const ${camel} = '${value}';`);
    } else {
      lines.push(`export declare const ${camel}: string;`);
    }
  }

  // ── Duration tokens (V10 deprecated aliases) ──────────────────────────────
  lines.push('');
  lines.push('// Duration tokens (V10 — deprecated aliases)');
  const v10Camels = [];

  for (const v11Camel of durationCamels) {
    const v10Camel = toV10CamelName(v11Camel);
    v10Camels.push(v10Camel);

    if (outputMode === 'js') {
      lines.push(`/** @deprecated Use \`${v11Camel}\` instead */`);
      lines.push(`export const ${v10Camel} = ${v11Camel};`);
    } else {
      lines.push(`/** @deprecated Use \`${v11Camel}\` instead */`);
      lines.push(`export declare const ${v10Camel}: string;`);
    }
  }

  // ── Easing map ────────────────────────────────────────────────────────────
  lines.push('');
  lines.push('// Easing tokens');

  if (outputMode === 'dts') {
    lines.push(
      "export declare const easings: Record<'standard' | 'entrance' | 'exit', Record<'productive' | 'expressive', string>>;"
    );
  } else {
    lines.push('export const easings = {');
    for (const easingName of ['standard', 'entrance', 'exit']) {
      lines.push(`  ${easingName}: {`);
      for (const mode of ['productive', 'expressive']) {
        const key = `easing-${easingName}-${mode}`;
        const value = tokenMap.get(key);
        if (value === undefined) {
          throw new Error(`Missing SD token: ${key}`);
        }
        lines.push(`    ${mode}: '${value}',`);
      }
      lines.push(`  },`);
    }
    lines.push('};');
  }

  // ── unstable_tokens ───────────────────────────────────────────────────────
  lines.push('');
  if (outputMode === 'dts') {
    lines.push('export declare const unstable_tokens: readonly string[];');
  } else {
    lines.push('export const unstable_tokens = [');
    for (const camel of durationCamels) lines.push(`  '${camel}',`);
    for (const v10 of v10Camels) lines.push(`  '${v10}',`);
    lines.push('];');
  }

  lines.push('');
  return lines.join('\n');
}

module.exports = {
  name: 'carbon/motion-js-tokens',
  format: carbonJsMotionTokensFormat,
};
