/**
 * Copyright IBM Corp. 2018, 2026
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

'use strict';

/**
 * Emits `scss/generated/_tokens.scss` from the motion DTCG tokens.
 *
 * Generates:
 *   - `$easings` Sass map  (standard/entrance/exit × productive/expressive)
 *   - V11 `$duration-*` variables
 *   - V10 `$fast-*` / `$moderate-*` / `$slow-*` deprecated aliases
 */

const FILE_BANNER = `// Code generated by @carbon/motion. DO NOT EDIT.
//
// Copyright IBM Corp. 2018, 2026
//
// This source code is licensed under the Apache-2.0 license found in the
// LICENSE file in the root directory of this source tree.
//
`;

/**
 * @param {{ dictionary: import('style-dictionary').Dictionary }} args
 * @returns {string}
 */
function carbonScssMotionTokensFormat({ dictionary }) {
  // Build a lookup from kebab token name → resolved value
  const tokenMap = new Map(
    dictionary.allTokens.map((t) => [t.name, t.value ?? t.$value])
  );

  const lines = [FILE_BANNER];

  // ── $easings map ──────────────────────────────────────────────────────────
  lines.push('/// Common component easings');
  lines.push('/// @type Map');
  lines.push('/// @access public');
  lines.push('/// @group @carbon/motion');
  lines.push('$easings: (');
  for (const easingName of ['standard', 'entrance', 'exit']) {
    lines.push(`  ${easingName}: (`);
    for (const mode of ['productive', 'expressive']) {
      const key = `easing-${easingName}-${mode}`;
      const value = tokenMap.get(key);
      if (value === undefined) {
        throw new Error(`Missing SD token: ${key}`);
      }
      lines.push(`    ${mode}: ${value},`);
    }
    lines.push(`  ),`);
  }
  lines.push(') !default;');
  lines.push('');

  // ── V11 duration variables ────────────────────────────────────────────────
  const durationTokens = dictionary.allTokens.filter((t) =>
    t.name.startsWith('duration-')
  );

  for (const token of durationTokens) {
    const description = token.$description ?? token.description ?? '';
    if (description) lines.push(`/// ${description}`);
    lines.push('/// @access public');
    lines.push('/// @type Duration');
    lines.push('/// @group @carbon/motion');
    lines.push(`$${token.name}: ${token.value ?? token.$value} !default;`);
    lines.push('');
  }

  // ── V10 deprecated aliases ────────────────────────────────────────────────
  lines.push('/// V10 backwards compatibility tokens');
  const v10Map = {
    'duration-fast-01': 'fast-01',
    'duration-fast-02': 'fast-02',
    'duration-moderate-01': 'moderate-01',
    'duration-moderate-02': 'moderate-02',
    'duration-slow-01': 'slow-01',
    'duration-slow-02': 'slow-02',
  };
  for (const [v11, v10] of Object.entries(v10Map)) {
    lines.push('/// @access public');
    lines.push('/// @deprecated');
    lines.push('/// @type Duration');
    lines.push('/// @group @carbon/motion');
    lines.push(`$${v10}: $${v11} !default;`);
    lines.push('');
  }

  return lines.join('\n');
}

module.exports = {
  name: 'carbon/motion-scss-tokens',
  format: carbonScssMotionTokensFormat,
};
