name: Contribution Buddy
# This workflow is triggered when a label is added to an issue.
on:
  issues:
    types: labeled

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v3
        with:
          github-token: ${{ github.token }}
          config-path: '.github/label-actions.yml'
          process-only: 'issues'
      