name: Contribution Buddy
# This workflow is triggered when a label is added to an issue.
on:
  issues:
    types: labeled

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@ade7bcd4c1b30de6ba8e556cc31301fd4f79ca65 #v3.1.0
        with:
          github-token: ${{ github.token }}
          config-path: '.github/label-actions.yml'
          process-only: 'issues'
      