name: Deploy

on:
  workflow_dispatch:

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Build project
        run: yarn build
      - name: Build React storybook
        run: yarn workspace @carbon/react build-storybook
      - name: Setup GitHub Pages folder
        run: |
          # Move static assets to the react subdirectory
          mv packages/react/storybook-static gh-pages

          # Setup CNAME record for React storybook
          echo 'staging.react.carbondesignsystem.com' > gh-pages/CNAME
      - name: Deploy to GitHub Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d gh-pages -u "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
