name: Mend Scan - Carbon Monorepo

on:
  schedule:
    - cron: '0 0 * * *' # Runs at Midnight UTC
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  mend-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Required to run the Mend Unified Agent .jar

      - name: Run Mend Scan
        env:
          WS_APIKEY: ${{ secrets.WS_APIKEY }}
          WS_USERKEY: ${{ secrets.WS_USERKEY }}
          WS_WSS_URL: ${{ secrets.WS_WSS_URL }}

          # Project Configuration
          WS_PRODUCTNAME: 'PSIRT_PRD0013444'
          WS_PROJECTNAME: 'GH_carbon'
        run: |
          # Download the latest Mend Unified Agent
          curl -L https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar -o wss-unified-agent.jar
          # Execute the scan
          java -jar wss-unified-agent.jar
