name: Next release (v12 alpha)

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'release tag (ie. v12.0.0-alpha.0)'
        type: string
        default: 'v12.0.0-alpha.0'
      dry_run:
        required: true
        description: 'Run dry run?'
        type: boolean
        default: true

jobs:
  build:
    name: Create Release
    if: github.ref == 'refs/heads/next'
    runs-on: ubuntu-latest-larger-disk
    timeout-minutes: 60
    # Needed as recommended by npm docs on publishing with provenance https://docs.npmjs.com/generating-provenance-statements
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --immutable --check-cache

      - name: Build project
        run: yarn build

      - name: Run Continuous Integration checks
        run: yarn ci-check

      - name: Publish packages under the `v12-alpha` dist tag
        run: |
          yarn lerna publish prerelease --preid alpha --pre-dist-tag v12-alpha \
            ${{ github.event.inputs.dry_run != 'true' && '--yes' || '' }}

      - name: Create git tag
        if: ${{ github.event.inputs.dry_run != 'true' }}
        run: |
          git tag -a "${{ github.event.inputs.tag }}" -m "${{ github.event.inputs.tag }}"
          git push origin "${{ github.event.inputs.tag }}"

