name: Next release (v12 alpha)

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        description: 'release tag (ie. v12.0.0-alpha.0)'
        type: string
        default: 'v12.0.0-alpha.0'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest-larger-disk
    timeout-minutes: 60
    # Needed as recommended by npm docs on publishing with provenance https://docs.npmjs.com/generating-provenance-statements
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --immutable --check-cache

      # For generating playwright json report for avt tests
      - name: Install browsers
        run: yarn playwright install --with-deps

      - name: Build project
        run: yarn build

      # Additional steps for generating playwright json report for avt tests
      - name: Build storybook
        run: yarn workspace @carbon/react storybook:v12:build
      - name: Run storybook
        id: storybook
        run: |
          npx serve -l 3000 packages/react/storybook-static-v12 &
          pid=$!
          echo ::set-output name=pid::"$pid"
      - uses: ./actions/wait-for-it
        with:
          URL: 'http://localhost:3000'
        timeout-minutes: 3
      - name: Run AVT
        if: github.repository == 'carbon-design-system/carbon'
        run: |
          yarn playwright test --project chromium --grep @avt
      - name: Stop storybook
        run: kill ${{ steps.storybook.outputs.pid }}
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #7.0.1
        with:
          name: playwright-avt-report
          path: .playwright

      - name: Run Continuous Integration checks
        run: yarn ci-check

      - name: Publish packages under the `v12-alpha` dist tag
        run:
          yarn lerna publish preminor --conventional-prerelease --preid alpha --pre-dist-tag v12-alpha

      - name: Create git tag
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git tag -a "${{ github.event.inputs.tag }}" -m "Release ${{ github.event.inputs.tag }}"
          git push origin "${{ github.event.inputs.tag }}"

      - name: Create Release
        id: create_release
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 #v9.0.0
        with:
          script: |
            github.rest.repos.createRelease({
              tag_name: '${{ github.event.inputs.tag }}',
              name: '${{ github.event.inputs.tag }}',
              draft: false,
              prerelease: true,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

