name: Promote Packages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./actions/sync-packages-to-latest
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
