name: Slack Office Hours Reminder - Dev

on:
  schedule:
    # Run every Tuesday at 09:00AM CT, 02:00PM UTC
    - cron: '0 14 * * TUE'

jobs:
  post-reminder-to-carbon-react:
    name: Post dev reminder to carbon-react
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "username": "Carbon Design System",
              "icon_url": "https://user-images.githubusercontent.com/3360588/192045905-5d9705af-92e2-4432-805e-15db98571e8b.png",
              "channel": "#carbon-react",
              "text": "Join us for Carbon Developer Office Hours!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Join us for Carbon Developer Office Hours!",
                    "emoji": true
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "image",
                  "image_url": "https://github.com/user-attachments/assets/e12fb5b9-9657-4e7b-b1a1-e1149cca8956",
                  "alt_text": "A terminal prompt symbol"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":thinking_face:   _Are you running into a weird bug you can’t resolve?_  \n\n_:question:  Do you have questions about using Carbon?_  \n\n :rocket:  _Would you like to discuss migrating from v10 to v11?_"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Carbon developer office hours* are a bi-weekly opportunity to discuss topics like these and get help from the team. Developers from the Carbon team will be available to help and answer questions. While it's very informal, please be prepared to screen share and show your issue!"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":yourlearning:  *Subscribe and add to your calendar*     :ibm-arrow-right::ibm-arrow-right::ibm-arrow-right:"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Subscribe",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "https://ec.yourlearning.ibm.com/w3/enrollment/event/10482832",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":memo:  *Sign up to get help in a future session*     :ibm-arrow-right::ibm-arrow-right::ibm-arrow-right:"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View the agenda",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "https://ibm.biz/carbon-dev-office-hours",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "divider"
                }
              ]
            }

  post-reminder-to-carbon-web-components:
    name: Post dev reminder to carbon-web-components
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "username": "Carbon Design System",
              "icon_url": "https://user-images.githubusercontent.com/3360588/192045905-5d9705af-92e2-4432-805e-15db98571e8b.png",
              "channel": "#carbon-web-components",
              "text": "Join us for Carbon Developer Office Hours!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Join us for Carbon Developer Office Hours!",
                    "emoji": true
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "image",
                  "image_url": "https://github.com/user-attachments/assets/e12fb5b9-9657-4e7b-b1a1-e1149cca8956",
                  "alt_text": "A terminal prompt symbol"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":thinking_face:   _Are you running into a weird bug you can’t resolve?_  \n\n_:question:  Do you have questions about using Carbon?_  \n\n :rocket:  _Would you like to discuss migrating from v10 to v11?_"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Carbon developer office hours* are a bi-weekly opportunity to discuss topics like these and get help from the team. Developers from the Carbon team will be available to help and answer questions. While it's very informal, please be prepared to screen share and show your issue!"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":yourlearning:  *Subscribe and add to your calendar*     :ibm-arrow-right::ibm-arrow-right::ibm-arrow-right:"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Subscribe",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "https://ec.yourlearning.ibm.com/w3/enrollment/event/10482832",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":memo:  *Sign up to get help in a future session*     :ibm-arrow-right::ibm-arrow-right::ibm-arrow-right:"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View the agenda",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "https://ibm.biz/carbon-dev-office-hours",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "divider"
                }
              ]
            }

  post-reminder-to-carbon-for-ibmproducts:
    name: Post dev reminder to carbon-for-ibmproducts
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "username": "Carbon Design System",
              "icon_url": "https://user-images.githubusercontent.com/3360588/192045905-5d9705af-92e2-4432-805e-15db98571e8b.png",
              "channel": "#carbon-for-ibmproducts",
              "text": "Join us for Carbon Developer Office Hours!",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Join us for Carbon Developer Office Hours!",
                    "emoji": true
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "image",
                  "image_url": "https://github.com/user-attachments/assets/e12fb5b9-9657-4e7b-b1a1-e1149cca8956",
                  "alt_text": "A terminal prompt symbol"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":thinking_face:   _Are you running into a weird bug you can’t resolve?_  \n\n_:question:  Do you have questions about using Carbon?_  \n\n :rocket:  _Would you like to discuss migrating from v10 to v11?_"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Carbon developer office hours* are a bi-weekly opportunity to discuss topics like these and get help from the team. Developers from the Carbon team will be available to help and answer questions. While it's very informal, please be prepared to screen share and show your issue!"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":yourlearning:  *Subscribe and add to your calendar*     :ibm-arrow-right::ibm-arrow-right::ibm-arrow-right:"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Subscribe",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "https://ec.yourlearning.ibm.com/w3/enrollment/event/10482832",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":memo:  *Sign up to get help in a future session*     :ibm-arrow-right::ibm-arrow-right::ibm-arrow-right:"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View the agenda",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "https://ibm.biz/carbon-dev-office-hours",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "divider"
                }
              ]
            }
