name: Carbon Champions Nomination Reminder

on:
  schedule:
    # Run every 2nd Wednesday of the month at 09:00AM CT, 02:00PM UTC
    - cron: '0 14 11-16 * WED'

jobs:
  post-reminder:
    name: Post Carbon Champions Nomination reminder to the carbon-team channel
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "username": "Carbon Design System",
              "icon_url": "https://user-images.githubusercontent.com/3360588/192045905-5d9705af-92e2-4432-805e-15db98571e8b.png",
              "channel": "#carbon-team",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": " :carbon: Carbon Champions Nomination :carbon:"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here Please provide your nominations - Devs | Designers | Internal | External - anyone you think has been doing amazing work in our community. :blue_heart: "
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":bluewolfarrow:  *Carbon Champions Nomination Form*  "
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Click Me",
                      "emoji": true
                    },
                    "value": "click_me_123",
                    "url": "https://airtable.com/shrkMzlvQhPBB6UnX",
                    "action_id": "button-action"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
